In [2]:
import pandas as pd
import numpy as np
import pydot as pyd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import LSTM
from keras import models
from keras.layers.normalization import BatchNormalization
from keras.models import model_from_json
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
import json

In [32]:
train = pd.read_csv('./output/giros_train_numeric.csv', index_col=0)
train.head()

Weekday of Fecha Referencia  Day of Fecha Referencia  \
id                                                         
1                             1                        1   
2                             1                        1   
3                             1                        1   
4                             1                        1   
5                             1                        1   

    Month of Fecha Referencia  Giros  
id                                    
1                           1   1115  
2                           2   5934  
3                           4  13417  
4                           5   2827  
5                           6  12283

In [33]:
X = train.drop(columns=["Giros"])
y = train["Giros"]

In [34]:
y = y.values.reshape(-1, 1)

In [35]:
enc = preprocessing.OneHotEncoder()
y = enc.fit_transform(y)

In [36]:
y = y.toarray()

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [44]:
number_classes = y.shape[1]
inshape = (X_train.shape[1],)


model = models.Sequential()  #creates the neural network layers:

model.add(layers.Dense(64, activation='elu', input_shape=inshape))
model.add(BatchNormalization())
model.add(layers.Dense(64, activation='elu'))

model.add(layers.Dense(number_classes, activation='sigmoid'))
model.compile(optimizer='adamax',
            loss='categorical_crossentropy',
            metrics=['accuracy'])

history = model.fit(X_train,
        y_train,
        epochs=50,
        batch_size=20,
        validation_data=(X_test, y_test))

results = model.evaluate(X_test, y_test)
print("\n")
print("Resultados: ",results)
print("\n")

Epoch 1/50
88/88 [==============================] - 0s 5ms/step - loss: 7.6034 - accuracy: 0.0000e+00 - val_loss: 7.6222 - val_accuracy: 0.0000e+00
Epoch 2/50
88/88 [==============================] - 0s 5ms/step - loss: 7.5183 - accuracy: 0.0011 - val_loss: 7.8580 - val_accuracy: 0.0023
Epoch 3/50
88/88 [==============================] - 0s 4ms/step - loss: 7.4159 - accuracy: 0.0029 - val_loss: 8.6527 - val_accuracy: 0.0000e+00
Epoch 4/50
88/88 [==============================] - 0s 4ms/step - loss: 7.3188 - accuracy: 0.0017 - val_loss: 9.5814 - val_accuracy: 0.0000e+00
Epoch 5/50
88/88 [==============================] - 0s 4ms/step - loss: 7.2647 - accuracy: 0.0040 - val_loss: 10.3205 - val_accuracy: 0.0000e+00
Epoch 6/50
88/88 [==============================] - 0s 4ms/step - loss: 7.2090 - accuracy: 0.0029 - val_loss: 10.8984 - val_accuracy: 0.0000e+00
Epoch 7/50
88/88 [==============================] - 0s 4ms/step - loss: 7.1599 - accuracy: 0.0046 - val_loss: 11.4835 - val_accuracy: 

In [21]:
y_pred = model.predict(X_test)
y_pred

array([[4.1979788e-18, 1.6612667e-14, 7.3570122e-10, ..., 9.9391451e-10,
        2.2657424e-21, 2.5378816e-19],
       [2.1751163e-10, 8.7514258e-16, 1.6170699e-09, ..., 5.6553545e-10,
        6.8459227e-12, 2.6731877e-15],
       [2.9973112e-21, 1.7851934e-14, 7.3161925e-09, ..., 4.5047108e-09,
        1.6736912e-22, 3.9079183e-21],
       ...,
       [1.0661739e-16, 5.4450262e-17, 1.6911366e-09, ..., 2.2236017e-09,
        4.5094039e-17, 5.5043385e-24],
       [4.4802595e-02, 8.4980472e-27, 3.2802927e-11, ..., 1.0268174e-11,
        7.7566755e-04, 1.4390125e-13],
       [4.3028641e-16, 1.1981029e-12, 2.7660567e-08, ..., 2.0647381e-08,
        1.2298359e-17, 8.3949295e-22]], dtype=float32)

In [22]:
prediction = enc.inverse_transform(y_pred)
prediction = prediction.reshape(prediction.shape[0])
prediction

array([ 8718,  3813,  5073,  4941, 10963,  6606,  7188,  1924,  2002,
        4331, 11894,  7240,  1676,  3720,  4802,  3411,  3300,  6209,
        3900,  5024,  2324,  2492,  4741,  9292,  1990,  1997, 13598,
        3863,  9294,  1718,  3649,  5093,  6424,  8712,  7807,  2307,
        7512,  7653,  2046,  5098,  6816,  1304,  5055,  8679,  5580,
        8309,  6743,  9215,  2912, 12254,  5505,  4056,  2590,  7240,
        1588,  3676,  3900,  3649,  1836,  4230,  6891,  4421, 12032,
        2721,  9037,  3664,  6678, 11449,  2080, 14388,  4371,  6539,
        2409,  6097, 12797,  1249,  8029,  1829,  4941,  4792, 11449,
        3048, 10618, 12032,  3364,  5623,  4576,  5278,  8366, 10735,
        1615,  7807,  8128,  4421,  9920,  5544,  2670,  1304, 12375,
        9017,  7465, 10891,  6444,  6251,  4860, 13582,  4834,  7532,
        8718,  8321,  4135,  9915,  7512,  4322,  4858,  2828, 10522,
        6691,  4401,  1587,  9030,  1883,  2840,  3428,  4249,  3258,
        4677,  7083,

In [23]:
y_test = enc.inverse_transform(y_test)
y_test = y_test.reshape(y_test.shape[0])
y_test

array([ 2692,  2495,  1853,  3747,  3417,  7557, 11155,  1254,  6313,
        1197,  6118,  5923,  2678,  5051,  1578,  3515,  9898,  4941,
        2779,  2164,  5043,  1570,  3776,  2423,  2690,  6222,  2877,
        2633, 10634,  2207,  5408, 13945,  3374,  5016,  6776,  2994,
        7490,  2240,  5427,  5434,  2121,  1330,  3966,  2790,  4311,
        2301,  3126,  4341,  4083,  9191,  4215,  7633, 10700,  5540,
        1727,  2471,  9107,  3148,  6109,  8187,  4533,  5896,  9412,
        9375,  5249,  2237, 10666,  6059,  8435,  7566,  5157,  2212,
        1614,  2404,  7762,  3357,  3026,  3790,  4011,  4966,  4635,
        1824,  4597,  3956,  4250,  2577,  1601,  9414,  1963,  6102,
        3798,  3418,  5965,  8213,  2785,  5778,  3923,  2030, 10811,
        7518, 15360, 10246,  4790,  2357,  3266,  3479,  8233,  2766,
        3405,  5850,  2322,  6122,  5739,  2735,  2008,  5219,  3787,
       13813,  5965,  3010,  6894,  6490,  8033,  3743,  7484,  4747,
        2476,  1881,

In [24]:
prediction_df = pd.DataFrame({'prediction': prediction,
                              'ground_truth': y_test,
                              'diff': prediction - y_test})
prediction_df

prediction  ground_truth  diff
0          8718          2692  6026
1          3813          2495  1318
2          5073          1853  3220
3          4941          3747  1194
4         10963          3417  7546
..          ...           ...   ...
434        1638          1235   403
435        5189          4834   355
436        1425          2024  -599
437        6081          8627 -2546
438        1695          1488   207

[439 rows x 3 columns]

In [ ]:
"""number_classes = y.shape[1]
inshape = (X_train.shape[1],)


model = models.Sequential()  #creates the neural network layers:

model.add(layers.Dense(512, activation='relu', input_shape=inshape))
model.add(layers.Dense(256, activation='relu'))
model.add(BatchNormalization())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))

model.add(layers.Dense(number_classes, activation='softmax'))
model.compile(optimizer='Nadam',
            loss='categorical_crossentropy',
            metrics=['accuracy'])

history = model.fit(X_train,
        y_train,
        epochs=50,
        batch_size=20,
        validation_data=(X_test, y_test))

results = model.evaluate(X_test, y_test)
print("\n")
print("Resultados: ",results)
print("\n")

23.8%
"""